# 感知机上机报告
谢昊君 1200015556 元培学院
感知机算法解决二元分类问题，分类见training data.

## 感知机算法简介
感知机(Perceptron)为一种二类分类的线性分类模型，输入为实例的特征向量，输出为实例类别，一般取+1、-1。对应于输入空间将实例进行线性划分的分离超平面。

假设输入空间$\mathscr{X}\subsetneqq\mathbf{R}^n$,输出空间$\mathscr{Y}=\{+1,-1\}$
$$f(x)=sign(wx+b)$$


$sign(x)$此处为符号函数，表示如下：
$$sign(x)=+1, x\geq 0;-1,x\lt0$$

### 数据线性可分性的定义:

给定数据集$T = \{(x_1,y_1),(x_2，y_2),....\}$, 其中$x_1\in\mathscr{X}=\mathbf{R}^n$,$\mathscr{Y}=\{+1,-1\}$，若存在某个超平面S:$wx+b=0$使得数据集中所有正实例点和负实例点正确划分到超平面两侧。
对$y_i=+1$,有$wx_i+b\gt0$;对$y_i=-1$,有$wx_i+b<0$，此时称数据集为线性可分。

### 损失函数-
$$L(w,b)=-\sum_{x_i\in M}y_i(wx_i+b)$$
其中M指误分类点集合。对正确分类的点，损失函数为0
对损失函数进行随机梯度下降法进行优化，即得更新标准。

对$w$有：
$$w\leftarrow w+\eta y_i x_i$$
对$b$有：
$$b\leftarrow b+\eta y_i$$

其中$\eta$为学习率，即最优化中的步长。

### 对偶形式的感知机
略
## 本文采取方法具体说明
（本文采用方法假定了训练集为线性可分集合）
在初始的权重向量设定下，计算此时的分类。函数为 $f(x)=wx-\theta$ （$\theta$与上文符号相反）

选取分类错误的样本中的第一个作为标准，更新权重向量。直到所有样本都正确分类。

按照老师讲义上的更新标准 $w_i(k+1)=w_i(k)+\eta(t(k)-y(k))x_i(k)$,在二元分类的简单感知机模型下，相当于上一部分简介中以$w\leftarrow w+2*\eta y_i x_i$标准更新权重矩阵，对应不同的学习率。本文采取方法依照老师讲义上为准。


## 实验结果
以8个样本点，采用0作为初始和权重向量后，以每次误分类的第一个样本为标准更新，最终将所有样本正确分类。权重矩阵结果如下。

| $x_1$|$x_2$ |$x_3$ |$\theta$|
|------|------|------|------|
| -0.4 | -0.2| -0.6 | -0.6|

即最终的分类函数为:
$$f(x)=-0.4x_1-0.2x_2-0.6x_3+0.6$$-

In [1]:
import numpy as np
import numpy.random as rd
from random import choice
training_data = [[0,0,0,1],[1,0,0,1],[0,1,0,1],[0,0,1,1],[1,1,0,1],[1,0,1,-1],[0,1,1,-1],[1,1,1,-1]]

In [2]:
training_data = np.array(training_data)
print(training_data)

[[ 0  0  0  1]
 [ 1  0  0  1]
 [ 0  1  0  1]
 [ 0  0  1  1]
 [ 1  1  0  1]
 [ 1  0  1 -1]
 [ 0  1  1 -1]
 [ 1  1  1 -1]]


In [3]:
# 前三列为特征，最后未一列为分类结果，-1或+1
feature = training_data[:,0:3]
output = training_data[:,3]

In [4]:
# 定义signal函数，将大于等于0定义为1，小于0定义为-1
def sign(x):
    return (x>=0)*2-1

In [5]:
# set initial weight and theta
# 权重向量选取可以随机一个比较小的值。此处直接选择为0.也可以写作：
# w = rd.rand(1,3)
# theta = rd.rand(1,1)
w = np.array([0,0,0])
theta = 0
learning_rate = 0.1

In [6]:
# 感知机算法中误差项的定义，因为只有两种分类，+1，-1，若分类正确则误差为0，若分类错误误差为+-2
errors = sign(feature.dot(w)-theta)- output
zero = np.zeros((feature.shape[0]))
# 算法训练直到所有误差项均为0为止((errors == 0).all() )，即上式为False时继续循环。
while (errors == 0).all() ==False:
    # 选取未正确分类的样本
    tmp = (errors == zero)
    # 每次均选取第一个未正确分类对象调整
    a = (feature[tmp!=True])[0]
    expected = output[tmp!=True][0]
    # 按照感知机算法的更新标准进行，
    w = w + learning_rate * (expected)*2*a
    theta = theta - learning_rate * expected * 2
    errors = sign(feature.dot(w)-theta)- output
    
# 此处算法亦可简化为感知机算法的对偶算法

In [7]:
#输出训练完毕后的权重向量、常数项和最后的误差项。
#结果显示所有
print (w)
print (theta)
print (errors)

[-0.4 -0.2 -0.6]
-0.6
[0 0 0 0 0 0 0 0]


In [8]:
# as classes
# 将以上写法改写为类的形式。
import numpy as np
import numpy.random as rd
class Perceptron:
    def __init__(self):
        self.learning_rate = 0.1
#         self.training_feature = training_feature
#         self.training_class = training_class
        self.w = []
        self.theta = []
        
    # 允许自定义learning rate
    def set_learning_rate(self,x=0.1):
        self.learning_rate = x
        
    def train(self,feature,output):
        wide = feature.shape[1]
        w = np.zeros((wide))
        theta = 0
        errors = sign(feature.dot(w)-theta)- output
        zero = np.zeros((feature.shape[0]))
        while (errors == 0).all() ==False:
            tmp = (errors == zero)
            a = (feature[tmp!=True])[0]
            expected = output[tmp!=True][0]
            w = w + self.learning_rate * (expected)*2*a
            theta = theta - self.learning_rate * expected * 2
            errors = sign(feature.dot(w)-theta)- output
        self.w = w
        self.theta = theta
    
    # 定义此算法下预测的过程。
    def predict(self,feature):
        return sign(feature.dot(self.w)-self.theta)

In [9]:
# 生成Perceptron对象并做测试
a = Perceptron()
a.set_learning_rate(0.3)
a.train(feature,output)

In [10]:
print(a.predict(np.array([[1,2,1],[1,3,1]])))

[-1 -1]


In [11]:
print(a.w)
print(a.theta)

[-0.6 -0.6 -1.2]
-1.2


In [12]:
b = Perceptron()
b.train(feature,output)

In [13]:
print(b.predict(feature))

[ 1  1  1  1  1 -1 -1 -1]
